### ISSUE TITLE
Oven reward payout failed / not authorized depositor

### ISSUE THREAD

**Issue by dansan566** [Tezsure/ctez#106]
Hey everyone,
we experienced an issue when sending rewards to ctez oven delegators. Most of the bakers do not send out the rewards from their baking address. It's common to send those via a payout address! 

**Hotfix for TRD user:**
We can redirect payments to the specific owners. However, this is not a scalable solution. 

**Suggestion:**
Please add the specific baker payout address within "authorized depositors" as well!

Is there a reason to limit depositors anyway? So why wouldn't you want to allow anybody else to add more collateral on your behalf by default? I'm curious to hear.

**Comment by jdsika** [comment]
Any updates on this one?

**Comment by nicolasochem** [comment]
The checker documentation [states](https://checker.readthedocs.io/en/latest/functional_spec.html#deposit-collateral-in-a-burrow) `Fails if the burrow does not exist, if the sender does not own said collateral, `. There is no rationale provided for this.

It may be better to open a ticket in the original ctez repo?

**Comment by berndoostrum** [comment]
I think making "everyone" selected by default could help[image](https://user-images.githubusercontent.com/12640891/146639559-211d5264-62f5-494f-9b12-9373162e466c.jpeg)

For users that need the whitelist functionality we can add a warning, or if the data of payout addresses is available somewhere we could import it automatically. ![image](https://user-images.githubusercontent.com/12640891/146639607-ea5d7d30-d752-4e49-9826-cee9f4b0de55.jpeg)

There can be legal reasons to limit depositors. Not sure about the exact specifications though.

**Comment by baketzforme** [comment]
When I created my oven, at first I selected `Everyone` because I thought, "Why wouldn't I want everyone/anyone to be able to deposit funds on my behalf?"

Then I saw this tooltip:

![Authorized Depositors](https://user-images.githubusercontent.com/41446296/146640363-dbb064aa-4379-4e4c-8fb1-94610238654d.png)

That makes it sound like if you allow everyone/anyone, they can also mint the ctez from your oven and cause you to be liquidated. So I changed from `Everyone` to using a whitelist because of that tooltip. Basically, it scared me into making the wrong decision.

I think a good solution is to fix that tooltip and make `Everyone` the default.
